public enum UnitType
{
    //Building
    Fountain,
    Core,
    Tower,
    //Actor
    TowerBullet,
    FireBall,
    FireBreath,
    Meteor,
    BigBang,
    EarthShatter,
    Earthquake,
    PoisonGas,
    PressurisedSteam,
    //Character
    Minion,
    Monster,
    SuperMonster,
    UltraMonster,
    //Character.Champion
    HatsuneMiku,
    HakureiReimu,
    Yukikaze,
    Serval,
    KizunaAI,
    testKiz,
}